INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100001, 'Juan', 'Pérez', 'Administrador', 5000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100002, 'María', 'García', 'Recepcionista', 1500000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100003, 'Pedro', 'Rodríguez', 'Recepcionista', 1500000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100004, 'Luis', 'Martínez', 'Limpieza', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100005, 'Ana', 'Lopez', 'Limpieza', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100006, 'Carlos', 'Hernández', 'Limpieza', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100007, 'Laura', 'Méndez', 'Limpieza', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100008, 'Jorge', 'Castro', 'Cocinero', 2000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100009, 'Lucía', 'Sánchez', 'Cocinero', 2000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100010, 'Sofía', 'Ramírez', 'Cocinero', 2000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100011, 'Pablo', 'González', 'Asistente', 1200000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100012, 'Valeria', 'Ortiz', 'Asistente', 1200000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100013, 'Miguel', 'Fernández', 'Asistente', 1200000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100014, 'Clara', 'Morales', 'Asistente', 1200000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100015, 'Tomás', 'Domínguez', 'Asistente', 1200000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100016, 'Raquel', 'Vega', 'Recreacionista', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100017, 'Gabriel', 'Rojas', 'Recreacionista', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100018, 'Isabel', 'Blanco', 'Salvavidas', 1000000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100019, 'Daniel', 'Mora', 'Conductor', 1500000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100020, 'Elena', 'Reyes', 'Celador', 1200000);

INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100021, 'Fernando', 'Alonso', 'Electricista', 1700000);


INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100022, 'Juan', 'Nuñez', 'Plomero', 1300000);


INSERT INTO EMPLEADOS (ID_EMPLEADO, NOMBRE, APELLIDO, CARGO, SALARIO)
VALUES (100023, 'Sandra', 'Gutierrez', 'Tecnico General', 3000000);