INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (1, TO_DATE('2024-01-03', 'YYYY-MM-DD'), 'completa', 1, 100004);

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (2, TO_DATE('2023-12-20', 'YYYY-MM-DD'), 'solo baños', 2, 100005);

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (3, TO_DATE('2024-04-24', 'YYYY-MM-DD'), 'solo cuarto', 3, 100006);

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (4, TO_DATE('2024-07-24', 'YYYY-MM-DD'), 'completa', 5, 100007);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (5, TO_DATE('2024-08-15', 'YYYY-MM-DD'), 'solo baños', 6, 100007);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (6, TO_DATE('2024-07-25', 'YYYY-MM-DD'), 'solo cuarto', 7, 100006); 

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (7, TO_DATE('2024-06-22', 'YYYY-MM-DD'), 'completa', 8, 100005);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (8, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'solo baños', 10, 100004); 

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (9, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 'solo cuarto', 11, 100004);

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (10, TO_DATE('2024-01-10', 'YYYY-MM-DD'), 'completa', 14, 100005);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (11, TO_DATE('2023-12-10', 'YYYY-MM-DD'), 'solo baños', 15, 100006);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (12, TO_DATE('2024-05-05', 'YYYY-MM-DD'), 'solo cuarto', 17, 100007);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (13, TO_DATE('2024-03-08', 'YYYY-MM-DD'), 'completa', 18, 100007);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (14, TO_DATE('2023-12-30', 'YYYY-MM-DD'), 'solo baños', 19, 100006);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (15, TO_DATE('2024-07-25', 'YYYY-MM-DD'), 'solo cuarto', 20, 100005);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (16, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 'completa', 26, 100004);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (17, TO_DATE('2024-01-30', 'YYYY-MM-DD'), 'solo cuarto', 27, 100004);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (18, TO_DATE('2024-01-16', 'YYYY-MM-DD'), 'solo baños', 28, 100005); 

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (19, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 'completa', 29, 100006);  

INSERT INTO limpieza (ID_LIMPIEZA, FECHA_LIMPIEZA, NOMBRE_LIMPIEZA, ID_HABITACION, ID_EMPLEADO)
VALUES (20, TO_DATE('2024-01-20', 'YYYY-MM-DD'), 'solo cuarto', 30, 100007);