INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (1, 100000, TO_DATE('2023-10-05', 'YYYY-MM-DD'), 'Transferencia', NULL, 1, NULL, NULL); -- Alpina

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (2, 75000, TO_DATE('2023-11-06', 'YYYY-MM-DD'), 'Transferencia', NULL, 2, NULL, NULL); -- Postobón

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (3, 60000, TO_DATE('2024-05-14', 'YYYY-MM-DD'), 'Transferencia', NULL, 3, NULL, NULL); -- Soyafood

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (4, 65000, TO_DATE('2024-09-03', 'YYYY-MM-DD'), 'Transferencia', NULL, 4, NULL, NULL); -- Primor

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (5, 500000, TO_DATE('2023-09-10', 'YYYY-MM-DD'), 'Transferencia', NULL, 5, NULL, NULL); -- Pescados y Mariscos La 14

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (6, 720000, TO_DATE('2024-01-08', 'YYYY-MM-DD'), 'Transferencia', NULL, 6, NULL, NULL); -- Cárnica del Valle

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (7, 80000, TO_DATE('2023-08-15', 'YYYY-MM-DD'), 'Transferencia', NULL, 7, NULL, NULL); -- Colombina

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (8, 350000, TO_DATE('2024-02-08', 'YYYY-MM-DD'), 'Transferencia', NULL, 8, NULL, NULL); -- La Fama

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (9, 90000, TO_DATE('2023-12-01', 'YYYY-MM-DD'), 'Transferencia', NULL, 9, NULL, NULL); -- Pasta Lasa

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (10, 90000, TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'Transferencia', NULL, 10, NULL, NULL); -- Diana

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (11, 73000, TO_DATE('2024-07-06', 'YYYY-MM-DD'), 'Transferencia', NULL, 11, NULL, NULL); -- Fruticultores de Colombia

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (12, 67000, TO_DATE('2024-05-06', 'YYYY-MM-DD'), 'Transferencia', NULL, 12, NULL, NULL); -- Colanta

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (13, 59000, TO_DATE('2024-07-03', 'YYYY-MM-DD'), 'Transferencia', NULL, 13, NULL, NULL); -- Alimentos Cárnicos Costa

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (14, 320000, TO_DATE('2024-06-06', 'YYYY-MM-DD'), 'Transferencia', NULL, 14, NULL, NULL); -- Bavaria

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (15, 64000, TO_DATE('2023-10-06', 'YYYY-MM-DD'), 'Transferencia', NULL, 15, NULL, NULL); -- Hortalizas y Frutas El Salado

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (16, 71000, TO_DATE('2024-02-01', 'YYYY-MM-DD'), 'Transferencia', NULL, 16, NULL, NULL); -- Vecchio

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (17, 80000, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 'Transferencia', NULL, 17, NULL, NULL); -- Bimbo

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (18, 68000, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 'Transferencia', NULL, 18, NULL, NULL); -- Frigorífico La Dorada

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (19, 59000, TO_DATE('2024-10-06', 'YYYY-MM-DD'), 'Transferencia', NULL, 19, NULL, NULL); -- DelHuerto

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (20, 72000, TO_DATE('2024-03-07', 'YYYY-MM-DD'), 'Transferencia', NULL, 20, NULL, NULL); -- Agropecuaria Los Andes

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (21, 65000, TO_DATE('2024-04-04', 'YYYY-MM-DD'), 'Transferencia', NULL, 21, NULL, NULL); -- Agropinos

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (22, 57000, TO_DATE('2023-06-08', 'YYYY-MM-DD'), 'Transferencia', NULL, 22, NULL, NULL); -- Fruteo


--Mantenimiento

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (23, 200000, TO_DATE('2023-06-15', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 1, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (24, 150000, TO_DATE('2023-07-20', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 2, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (25, 300000, TO_DATE('2024-04-10', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 3, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (26, 150000, TO_DATE('2022-12-25', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 4, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (27, 200000, TO_DATE('2024-01-18', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 5, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (28, 100000, TO_DATE('2022-06-05', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 6, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (29, 400000, TO_DATE('2023-07-22', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 7, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (30, 250000, TO_DATE('2022-12-19', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 8, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (31, 180000, TO_DATE('2023-03-11', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 9, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (32, 120000, TO_DATE('2024-01-30', 'YYYY-MM-DD'), 'Transferencia', NULL, NULL, 10, NULL);


--Reservaciones

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (33, 4000000, TO_DATE('2023-12-25', 'YYYY-MM-DD'), 'Tarjeta', 1, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (34, 1000000, TO_DATE('2023-11-20', 'YYYY-MM-DD'), 'Efectivo', 2, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (35, 500000, TO_DATE('2024-04-12', 'YYYY-MM-DD'), 'Pago Movil', 3, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (36, 2500000, TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'Efectivo', 4, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (37, 1800000, TO_DATE('2024-07-20', 'YYYY-MM-DD'), 'Tarjeta', 5, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (38, 900000, TO_DATE('2024-08-08', 'YYYY-MM-DD'), 'Pago Movil', 6, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (39, 1600000, TO_DATE('2024-07-19', 'YYYY-MM-DD'), 'Tarjeta', 7, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (40, 3000000, TO_DATE('2024-06-17', 'YYYY-MM-DD'), 'Pago Movil', 8, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (41, 700000, TO_DATE('2024-12-01', 'YYYY-MM-DD'), 'Efectivo', 9, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (42, 1500000, TO_DATE('2024-07-06', 'YYYY-MM-DD'), 'Efectivo', 10, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (43, 3500000, TO_DATE('2024-05-12', 'YYYY-MM-DD'), 'Efectivo', 11, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (44, 2200000, TO_DATE('2024-12-03', 'YYYY-MM-DD'), 'Tarjeta', 12, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (45, 2800000, TO_DATE('2025-01-07', 'YYYY-MM-DD'), 'Tarjeta', 13, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (46, 1400000, TO_DATE('2023-12-25', 'YYYY-MM-DD'), 'Tarjeta', 14, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (47, 900000, TO_DATE('2023-11-17', 'YYYY-MM-DD'), 'Efectivo', 15, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (48, 1300000, TO_DATE('2024-10-10', 'YYYY-MM-DD'), 'Pago Movil', 16, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (49, 1100000, TO_DATE('2024-04-28', 'YYYY-MM-DD'), 'Efectivo', 17, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (50, 1800000, TO_DATE('2024-03-03', 'YYYY-MM-DD'), 'Efectivo', 18, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (51, 3200000, TO_DATE('2023-12-21', 'YYYY-MM-DD'), 'Tarjeta', 19, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (52, 1500000, TO_DATE('2024-07-18', 'YYYY-MM-DD'), 'Pago Movil', 20, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (53, 2700000, TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'Tarjeta', 21, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (54, 2300000, TO_DATE('2024-10-03', 'YYYY-MM-DD'), 'Tarjeta', 22, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (55, 3000000, TO_DATE('2024-10-13', 'YYYY-MM-DD'), 'Tarjeta', 23, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (56, 4000000, TO_DATE('2025-01-15', 'YYYY-MM-DD'), 'Tarjeta', 24, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (57, 1500000, TO_DATE('2024-12-08', 'YYYY-MM-DD'), 'Efectivo', 25, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (58, 300000, TO_DATE('2023-12-28', 'YYYY-MM-DD'), 'Efectivo', 26, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (59, 1900000, TO_DATE('2024-01-20', 'YYYY-MM-DD'), 'Tarjeta', 27, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (60, 2570000, TO_DATE('2024-01-12', 'YYYY-MM-DD'), 'Efectivo', 28, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (61, 700000, TO_DATE('2024-06-13', 'YYYY-MM-DD'), 'Efectivo', 29, Null, Null, NULL);

INSERT INTO facturacion (ID_FACTURA, MONTO, FECHA_FACTURA, METODO_PAGO, ID_RESERVACION, ID_PROVEEDOR, ID_MANTENIMIENTO, ID_HABITACION)
VALUES (62, 1000000, TO_DATE('2024-01-13', 'YYYY-MM-DD'), 'Efectivo', 30, Null, Null, NULL);


