
INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(1, '5','Comida excelente, me encantó todo', TO_DATE('2024-01-20', 'YYYY-MM-DD'),100001);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(2, '5','Servicio perfecto, volveré seguro', TO_DATE('2024-01-20', 'YYYY-MM-DD'),100002);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(3, '4','Comida buena, pero el servicio puede mejorar', TO_DATE('2024-05-05', 'YYYY-MM-DD'),100003);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(4, '3',null, TO_DATE('2025-01-20', 'YYYY-MM-DD'),100004);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(5, '4','Ambiente agradable, aunque la comida estuvo bien', TO_DATE('2024-08-05', 'YYYY-MM-DD'),100005);


INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(6, '2','El servicio fue muy lento, no me gustó', TO_DATE('2024-09-01', 'YYYY-MM-DD'),100006);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(7, '1','Comida terrible, no volveré', TO_DATE('2024-08-02', 'YYYY-MM-DD'),100007);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(8, '5','Todo estuvo increíble', TO_DATE('2024-06-30', 'YYYY-MM-DD'),100008);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(9, '2',null, TO_DATE('2025-02-23', 'YYYY-MM-DD'),100009);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(10, '3','No está mal, pero podría ser mejor', TO_DATE('2024-08-02', 'YYYY-MM-DD'),100010);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(11, '4','Buen lugar, pero el servicio un poco lento', TO_DATE('2024-05-27', 'YYYY-MM-DD'),100011);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(12, '1',null, TO_DATE('2025-01-20', 'YYYY-MM-DD'),100012);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(13, '5',null, TO_DATE('2025-01-20', 'YYYY-MM-DD'),100013);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(14, '3','Regular, nada especial', TO_DATE('2024-01-25', 'YYYY-MM-DD'),100014);


INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(15, '5', 'Excelente atención y comida deliciosa', TO_DATE('2024-01-15', 'YYYY-MM-DD'), 100015);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(16, '5', null, TO_DATE('2024-11-15', 'YYYY-MM-DD'), 100016);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(17, '5', 'Servicio de primera, lo recomiendo sin dudas', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 100017);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(18, '5', 'Uno de los mejores lugares que he visitado', TO_DATE('2024-03-20', 'YYYY-MM-DD'), 100018);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(19, '3', 'La comida estuvo bien, pero el lugar era ruidoso', TO_DATE('2024-01-27', 'YYYY-MM-DD'), 100019);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(20, '4', 'Buena comida pero el servicio fue un poco lento', TO_DATE('2024-08-01', 'YYYY-MM-DD'), 100020);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(21, '4', null, TO_DATE('2025-02-15', 'YYYY-MM-DD'), 100021);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(22, '3', null, TO_DATE('2024-12-27', 'YYYY-MM-DD'), 100022);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(23, '2', null, TO_DATE('2024-11-15', 'YYYY-MM-DD'), 100023);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(24, '1', null, TO_DATE('2025-02-10', 'YYYY-MM-DD'), 100024);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(25, '2', null, TO_DATE('2025-02-10', 'YYYY-MM-DD'), 100025);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(26, '1', null, TO_DATE('2025-01-05', 'YYYY-MM-DD'), 100026);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(27, '5', 'Me encantó todo, regresaré sin duda', TO_DATE('2024-02-03', 'YYYY-MM-DD'), 100027);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(28, '3', null, TO_DATE('2025-01-20', 'YYYY-MM-DD'), 100028);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(29, '4', 'Un buen lugar, pero puede mejorar en algunos detalles', TO_DATE('2024-08-01', 'YYYY-MM-DD'), 100029);

INSERT INTO Valoracion (ID_VALORACION, PUNTUACION, COMENTARIO, FECHA_VALORACION, ID_CLIENTE)
VALUES 
(30, '2', 'No me gustó el ambiente, demasiado ruidoso', TO_DATE('2024-01-27', 'YYYY-MM-DD'), 100030);
