INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100001, 'Juan', 'Pérez', 'Carrera 7 #45-10', 3001234567, 'juan.perez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100002, 'Ana', 'Gómez', 'Calle 10 #23-45', 3019876543, 'ana.gomez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100003, 'Carlos', 'López', 'Avenida El Poblado #25-60', 3021122334, 'carlos.lopez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100004, 'Lucía', 'Martínez', 'Calle 100 #15-30', 3035566778, 'lucia.martinez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100005, 'Miguel', 'Hernández', 'Carrera 50 #32-16', 3043344556, 'miguel.hernandez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100006, 'Sergio', 'Aza', 'Calle 5A #14-12', 3051234567, 'sergio.aza@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100007, 'Julian', 'Hernandez', 'Carrera 15 #50-24', 3069876543, 'julian.hernandez@hotmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100008, 'Jesus', 'Pachon', 'Calle 70 #20-89', 3071122334, 'jesus.pachon@hotmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100009, 'Santiago', 'Martínez', 'Avenida Boyacá #55-90', 3085566778, 'santiago.martinez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100010, 'Miguel', 'Rojas', 'Carrera 10 #43-12', 3093344556, 'miguel.rojas@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100011, 'Juan', 'Ardila', 'Calle Madero #25', 1234567890, 'juan.ardila@gmail.com', 'Mexicano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100012, 'Marisol', 'Ocampo', 'Calle 16 de Septiembre 560', 9876543210, 'marisol.ocampo@gmail.com', 'Mexicano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100013, 'Mario', 'Aza', 'Avenida Corrientes 1234', 1122334455, 'mario.aza@gmail.com', 'Argentino');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100014, 'María', 'Echeverry', 'Calle San Martín 987', 5566778899, 'maria.echeverry@gmail.com', 'Argentino');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100015, 'Isabella', 'Bohorquez', 'Calle Rivadavia 567', 3344556677, 'isabella.bohorquez@gmail.com', 'Argentino');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100016, 'María', 'Gutierrez', 'Calle Gran Vía 45', 123456789, 'maria.gutierrez@hotmail.com', 'Español');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100017, 'Ana', 'Sánchez', 'Calle 16 de Septiembre 560', 9876543210, 'ana.sanchez@hotmail.com', 'Mexicano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100018, 'Carlos', 'Castro', 'Calle de Alcalá 98', 112233456, 'carlos.castro@gmail.com', 'Español');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100019, 'Armando', 'Casas', 'Avenida Diagonal 600', 556677889, 'armando.casas@gmail.com', 'Español');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100020, 'Andrea', 'Méndez', 'Calle Mayor 22', 334455667, 'andrea.mendez@gmail.com', 'Español');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100021, 'Gabriel', 'Salazar', 'Calle 22 #11-20', 3101234567, 'gabriel.salazar@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100022, 'Fernanda', 'Lopez', 'Carrera 90 #22-45', 3119876543, 'fernanda.lopez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100023, 'José', 'Martínez', 'Calle 45 #33-12', 3121122334, 'jose.martinez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100024, 'Valentina', 'Hernandez', 'Avenida 15 #34-56', 3135566778, 'valentina.hernandez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100025, 'Diego', 'Alvarez', 'Calle 7 #89-10', 3143344556, 'diego.alvarez@gmail.com', 'Colombiano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100026, 'Luis', 'Pérez', 'Calle Libertador 450', 2345678901, 'luis.perez@gmail.com', 'Mexicano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100027, 'Claudia', 'Jiménez', 'Avenida Juárez 1234', 8765432109, 'claudia.jimenez@gmail.com', 'Mexicano');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100028, 'Roberto', 'Gutiérrez', 'Calle Rivadavia 890', 2233445566, 'roberto.gutierrez@gmail.com', 'Argentino');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100029, 'Elena', 'Fernández', 'Calle de Vallehermoso 45', 3344556678, 'elena.fernandez@gmail.com', 'Español');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL, NACIONALIDAD)
VALUES (100030, 'Javier', 'Ramírez', 'Calle Almagro 67', 4455667789, 'javier.ramirez@gmail.com', 'Español');