-- Temporada Alta
INSERT INTO TEMPORADA (ID_TEMPORADA, NOMBRE_TEMPORADA, FECHA_INICIO, FECHA_FIN)
VALUES 
(1, 'Temporada Alta', TO_DATE('2023-11-15', 'YYYY-MM-DD'), TO_DATE('2024-01-20', 'YYYY-MM-DD'));

INSERT INTO TEMPORADA (ID_TEMPORADA, NOMBRE_TEMPORADA, FECHA_INICIO, FECHA_FIN)
VALUES
(2, 'Temporada Alta', TO_DATE('2024-05-11', 'YYYY-MM-DD'), TO_DATE('2024-07-19', 'YYYY-MM-DD'));

INSERT INTO TEMPORADA (ID_TEMPORADA, NOMBRE_TEMPORADA, FECHA_INICIO, FECHA_FIN)
VALUES
(3, 'Temporada Alta', TO_DATE('2024-11-15', 'YYYY-MM-DD'), TO_DATE('2025-01-20', 'YYYY-MM-DD'));

-- Temporada Baja
INSERT INTO TEMPORADA (ID_TEMPORADA, NOMBRE_TEMPORADA, FECHA_INICIO, FECHA_FIN)
VALUES 
(4, 'Temporada Baja', TO_DATE('2024-01-21', 'YYYY-MM-DD'), TO_DATE('2024-05-10', 'YYYY-MM-DD'));

INSERT INTO TEMPORADA (ID_TEMPORADA, NOMBRE_TEMPORADA, FECHA_INICIO, FECHA_FIN)
VALUES 
(5, 'Temporada Baja', TO_DATE('2024-07-20', 'YYYY-MM-DD'), TO_DATE('2024-11-14', 'YYYY-MM-DD'));
