INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (1, 'Huevos Pericos', 8000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (2, 'Caldo de Costilla', 10000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (3, 'Arepa de Huevo', 3000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (4, 'Tamal', 6000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (5, 'Changua', 5000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (6, 'Huevos Revueltos', 7000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (7, 'Arroz con Pollo', 8000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (8, 'Lasaña', 12000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (9, 'Carne al Barril', 15000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (10, 'Mojarra', 23000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (11, 'Bagre', 20000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (12, 'Pollo Asado', 18000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (13, 'Ajiaco', 15000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (14, 'Risotto de Caviar', 30000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (15, 'Bandeja Paisa', 16000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (16, 'Pollo a la Naranja', 20000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (17, 'Pollo al Curry', 20000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (18, 'Trucha', 22000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (19, 'Mondongo', 12000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (20, 'Arroz con Camarones', 22000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (21, 'Pizza', 12000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (22, 'Hamburguesa', 10000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (23, 'Marzocada', 20000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (24, 'Hot Dog', 7000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (25, 'Salchipapa', 8000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (26, 'Empanadas', 1500);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (27, 'Coca Cola Personal', 3000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (28, 'Agua Mineral', 2000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (29, 'Agua con Gas', 2500);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (30, 'Colombiana Personal', 3000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (31, 'Pepsi Personal', 3000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (32, 'Poker', 5000);

INSERT INTO RESTAURANTE (ID_PLATO, NOMBRE, PRECIO)
VALUES (33, 'Aguila', 5000);
