INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (1, TO_DATE('2023-06-15', 'YYYY-MM-DD'), 'Piscina', 100022); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (2, TO_DATE('2023-07-20', 'YYYY-MM-DD'), 'Cancha de Tenis', 100023); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (3, TO_DATE('2024-04-10', 'YYYY-MM-DD'), 'Cancha Futbol', 100023); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (4, TO_DATE('2022-12-25', 'YYYY-MM-DD'), 'Cancha Volei', 100023); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (5, TO_DATE('2024-01-18', 'YYYY-MM-DD'), 'Cancha Basket', 100023); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (6, TO_DATE('2022-06-05', 'YYYY-MM-DD'), 'Zona de Pesca', 100022); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (7, TO_DATE('2023-07-22', 'YYYY-MM-DD'), 'Spa', 100022); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (8, TO_DATE('2022-12-19', 'YYYY-MM-DD'), 'Bar', 100021); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (9, TO_DATE('2023-03-11', 'YYYY-MM-DD'), 'Minigolf', 100023); 

INSERT INTO MANTENIMIENTO (ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ZONA, ID_EMPLEADO)
VALUES (10, TO_DATE('2024-01-30', 'YYYY-MM-DD'), 'Sala Comun', 100021);