INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (1, 'Sencilla', 'Reservado', TO_DATE('2023-12-25', 'YYYY-MM-DD'), TO_DATE('2024-01-06', 'YYYY-MM-DD'), 100001, 1, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (2, 'Doble', 'Reservado', TO_DATE('2023-11-20', 'YYYY-MM-DD'), TO_DATE('2024-01-06', 'YYYY-MM-DD'), 100002, 2, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (3, 'Familiar', 'Reservado', TO_DATE('2024-04-12', 'YYYY-MM-DD'), TO_DATE('2024-05-05', 'YYYY-MM-DD'), 100003, 3, 4);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (4, 'Sencilla', 'Reservado', TO_DATE('2025-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-20', 'YYYY-MM-DD'), 100004, 4, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (5, 'Doble', 'Reservado', TO_DATE('2024-07-20', 'YYYY-MM-DD'), TO_DATE('2024-08-05', 'YYYY-MM-DD'), 100005, 5, 5);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (6, 'Familiar', 'Reservado', TO_DATE('2024-08-08', 'YYYY-MM-DD'), TO_DATE('2024-09-01', 'YYYY-MM-DD'), 100006, 6, 5);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (7, 'Sencilla', 'Reservado', TO_DATE('2024-07-19', 'YYYY-MM-DD'), TO_DATE('2024-08-02', 'YYYY-MM-DD'), 100007, 7, 2);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (8, 'Doble', 'Reservado', TO_DATE('2024-06-17', 'YYYY-MM-DD'), TO_DATE('2024-06-30', 'YYYY-MM-DD'), 100008, 8, 2);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (9, 'Familiar', 'Reservado', TO_DATE('2024-12-01', 'YYYY-MM-DD'), TO_DATE('2025-02-23', 'YYYY-MM-DD'), 100009, 9, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (10, 'Sencilla', 'Reservado', TO_DATE('2024-07-06', 'YYYY-MM-DD'), TO_DATE('2024-08-02', 'YYYY-MM-DD'), 100010, 10, 2);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (11, 'Doble', 'Reservado', TO_DATE('2024-05-12', 'YYYY-MM-DD'), TO_DATE('2024-05-27', 'YYYY-MM-DD'), 100011, 11, 2);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (12, 'Familiar', 'Reservado', TO_DATE('2024-12-03', 'YYYY-MM-DD'), TO_DATE('2025-01-20', 'YYYY-MM-DD'), 100012, 12, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (13, 'Sencilla', 'Reservado', TO_DATE('2025-01-07', 'YYYY-MM-DD'), TO_DATE('2025-01-20', 'YYYY-MM-DD'), 100013, 13, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (14, 'Doble', 'Reservado',TO_DATE('2023-12-25', 'YYYY-MM-DD'), TO_DATE('2024-01-25', 'YYYY-MM-DD'), 100014, 14, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (15, 'Familiar', 'Reservado',TO_DATE('2023-11-17', 'YYYY-MM-DD'), TO_DATE('2024-01-15', 'YYYY-MM-DD'), 100015, 15, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (16, 'Sencilla', 'Reservado', TO_DATE('2024-10-10', 'YYYY-MM-DD'), TO_DATE('2024-11-15', 'YYYY-MM-DD'), 100016, 16, 5);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (17, 'Doble', 'Reservado', TO_DATE('2024-04-28', 'YYYY-MM-DD'), TO_DATE('2024-05-10', 'YYYY-MM-DD'), 100017, 17, 4);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (18, 'Familiar', 'Reservado', TO_DATE('2024-03-03', 'YYYY-MM-DD'), TO_DATE('2024-03-20', 'YYYY-MM-DD'), 100018, 18, 4);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (19, 'Sencilla', 'Reservado', TO_DATE('2023-12-21', 'YYYY-MM-DD'), TO_DATE('2024-01-27', 'YYYY-MM-DD'), 100019, 19, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (20, 'Doble', 'Reservado',TO_DATE('2024-07-18', 'YYYY-MM-DD'), TO_DATE('2024-08-01', 'YYYY-MM-DD'), 100020, 20, 2);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (21, 'Sencilla', 'Reservado', TO_DATE('2025-01-01', 'YYYY-MM-DD'),  TO_DATE('2025-02-15', 'YYYY-MM-DD'), 100021, 21, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (22, 'Doble', 'Reservado', TO_DATE('2024-10-03', 'YYYY-MM-DD'),  TO_DATE('2024-12-27', 'YYYY-MM-DD'), 100022, 22, 5);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (23, 'Sencilla', 'Reservado', TO_DATE('2024-10-13', 'YYYY-MM-DD'),  TO_DATE('2024-11-15', 'YYYY-MM-DD'), 100023, 23, 5);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (24, 'Doble', 'Reservado', TO_DATE('2025-01-15', 'YYYY-MM-DD'),  TO_DATE('2025-02-10', 'YYYY-MM-DD'), 100024, 24, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (25, 'Sencilla', 'Reservado', TO_DATE('2024-12-08', 'YYYY-MM-DD'),  TO_DATE('2025-02-10', 'YYYY-MM-DD'), 100025, 25, 3);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (26, 'Doble', 'En uso', TO_DATE('2023-12-28', 'YYYY-MM-DD'),  TO_DATE('2025-01-05', 'YYYY-MM-DD'), 100026, 26, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (27, 'Sencilla', 'Reservado', TO_DATE('2024-01-20', 'YYYY-MM-DD'),  TO_DATE('2024-02-03', 'YYYY-MM-DD'), 100027, 27, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (28, 'Doble', 'Reservado', TO_DATE('2024-01-12', 'YYYY-MM-DD'),  TO_DATE('2025-01-20', 'YYYY-MM-DD'), 100028, 28, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (29, 'Sencilla', 'Reservado', TO_DATE('2024-06-13', 'YYYY-MM-DD'),  TO_DATE('2024-08-01', 'YYYY-MM-DD'), 100029, 29, 2);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (30, 'Doble', 'Reservado', TO_DATE('2024-01-13', 'YYYY-MM-DD'),  TO_DATE('2024-01-27', 'YYYY-MM-DD'), 100030, 30, 1);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (31, 'Sencilla', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (32, 'Doble', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (33, 'Familiar', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (34, 'Sencilla', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (35, 'Doble', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (36, 'Familiar', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (37, 'Sencilla', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (38, 'Doble', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (39, 'Familiar', 'Disponible', NULL, NULL, NULL, NULL, NULL);

INSERT INTO HABITACIONES (ID_HABITACION, TIPO_HABITACION, ESTADO, FECHA_CHECK_IN, FECHA_CHECK_OUT, ID_CLIENTE, ID_RESERVACION, ID_TEMPORADA)
VALUES (40, 'Sencilla', 'Disponible', NULL, NULL, NULL, NULL, NULL);